{
	"id": "AVG-1091",
	"advisories": [
		{
			"id": "AVG-1091",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Medium"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1091"
				}
			]
		},
		{
			"id": "ASA-202002-1",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202002-1"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2020-7471",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-7471"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "python-django"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "3.0.3-1"
					}
				],
				"fixed": [
					"3.0.3-1"
				]
			}
		}
	]
}
