{
	"id": "AVG-1518",
	"advisories": [
		{
			"id": "AVG-1518",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Low"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1518"
				}
			]
		},
		{
			"id": "ASA-202102-18",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202102-18"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-3281",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-3281"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "python-django"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "3.1.6-1"
					}
				],
				"fixed": [
					"3.1.6-1"
				]
			}
		}
	]
}
