{
	"id": "AVG-1722",
	"advisories": [
		{
			"id": "AVG-1722",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "High"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1722"
				}
			]
		},
		{
			"id": "ASA-202103-25",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202103-25"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-1870",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-1870"
				}
			]
		},
		{
			"id": "CVE-2021-1801",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-1801"
				}
			]
		},
		{
			"id": "CVE-2021-1799",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-1799"
				}
			]
		},
		{
			"id": "CVE-2021-1789",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-1789"
				}
			]
		},
		{
			"id": "CVE-2021-1765",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-1765"
				}
			]
		},
		{
			"id": "CVE-2020-29623",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-29623"
				}
			]
		},
		{
			"id": "CVE-2020-27918",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2020-27918"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "wpewebkit"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "2.30.6-1"
					}
				],
				"fixed": [
					"2.30.6-1"
				]
			}
		}
	]
}
