{
	"id": "AVG-1593",
	"advisories": [
		{
			"content": {
				"id": "ASA-202102-28",
				"references": [
					{
						"source": "security.archlinux.org",
						"url": "https://security.archlinux.org/ASA-202102-28"
					}
				]
			},
			"ecosystems": [
				"arch"
			]
		},
		{
			"content": {
				"id": "ASA-202102-28",
				"references": [
					{
						"source": "security.archlinux.org",
						"url": "https://security.archlinux.org/ASA-202102-28"
					}
				]
			},
			"ecosystems": [
				"arch"
			]
		},
		{
			"content": {
				"id": "AVG-1593",
				"severity": [
					{
						"type": "vendor",
						"source": "security.archlinux.org",
						"vendor": "Medium"
					}
				],
				"references": [
					{
						"source": "security.archlinux.org",
						"url": "https://security.archlinux.org/AVG-1593"
					}
				]
			},
			"ecosystems": [
				"arch"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-23336",
				"references": [
					{
						"source": "security.archlinux.org",
						"url": "https://security.archlinux.org/CVE-2021-23336"
					}
				]
			},
			"ecosystems": [
				"arch"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"fix_status": {
							"class": "fixed"
						},
						"package": {
							"name": "python-django"
						},
						"affected": {
							"type": "pacman",
							"range": [
								{
									"lt": "3.1.7-1"
								}
							],
							"fixed": [
								"3.1.7-1"
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "arch",
		"raws": [
			"vuls-data-raw-arch/AVG-1593.json"
		]
	}
}
